slam_toolbox:
  ros__parameters:
    use_sim_time: true

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    mode: mapping
    resolution: 0.02
    max_laser_range: 8.0

    minimum_time_interval: 0.05
    transform_publish_period: 0.05
    map_update_interval: 0.3
    enable_interactive_mode: true

    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    throttle_scans: 1